### PR TITLE
UI: MenuAction

### PR DESCRIPTION
**Pull request by goldsteinsveta**
#51 fixed

Design reference:
Screenshot 2021-04-23 at 17 49 38

### CODE REVIEW

**Comment by hbulgarini** [comment]
I think i would set this PR as draft until PR #83  is merged.

**Comment by wirednkod** [comment]
I agree with @hbulgarini

**Comment by goldsteinsveta** [comment]
Conflicts should be resolved after #83

**Review by wirednkod — APPROVED** [review]

**Review by wirednkod — APPROVED** [review]

**Review by hbulgarini — APPROVED** [review]
looks good!

**Pull request merged**
