### PR TITLE
Override provider URLs in Docker container runtime

### LINKED ISSUE #201: Build Docker image on CI and publish to docker hub
Follow up on #87

### PR DESCRIPTION
**Pull request by tomusdrw**
A hacky workaround to make sure we don't rebuild the app while starting the docker image.

Basically we replace the default URL with the one provided using ENV variables.

Closes #201 

Companion to: https://github.com/paritytech/parity-bridges-common/pull/1047

### CODE REVIEW

**Review by hbulgarini — APPROVED** [review]
Let's merge it and integrate it with the PR from the common project.

**Comment by hbulgarini** [comment]
@tomusdrw  feel free to merge when you consider the PR is ready.

**Comment by tomusdrw** [comment]
@hbulgarini thanks! Do you mind publishing the release whenever you feel it's the right time? This would allow https://github.com/paritytech/parity-bridges-common/pull/1047 to move forward.

**Comment by hbulgarini** [comment]
> @hbulgarini thanks! Do you mind publishing the release whenever you feel it's the right time? This would allow [paritytech/parity-bridges-common#1047](https://github.com/paritytech/parity-bridges-common/pull/1047) to move forward.

Sure. I think this PR is enough to justify a new release.

**Comment by hbulgarini** [comment]
CC @tomusdrw: https://github.com/paritytech/parity-bridges-ui/releases/tag/v1.03

**Pull request merged**
